### ISSUE TITLE
Flutter SDK not found. Define location with flutter.sdk in the local.properties file.

### ISSUE THREAD

**Issue by ShaheenDevelopers** [HoussemTN/Al-quran-Al-karim#7]
I update my flutter SDK but still showing same error. how to load project in android studio it's showing error.
**Flutter SDK not found. Define location with flutter.sdk in the local.properties file.**

**Comment by HoussemTN** [comment]
Sorry to be late. This question is not related to the project; you need to define your Flutter SDK in your local.properties.
