### ISSUE TITLE
issues when run the app

### ISSUE THREAD

**Issue by Zakiabouzahra** [HoussemTN/Al-quran-Al-karim#8]
Launching lib\main.dart on MAR LX1A in debug mode...
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.6.9/lib/src/gesture/extended_image_slide_page_route.dart:331:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/cupertino/route.dart:524:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/C:/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.6.9/lib/src/extended_image.dart:701:44: Error: No named parameter with the name 'nullOk'.
    _invertColors = MediaQuery.of(context, nullOk: true)?.invertColors ??
                                           ^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/media_query.dart:818:25: Context: Found this candidate, but the arguments don't match.

  static MediaQueryData of(BuildContext context) {
                        ^^

FAILURE: Build failed with an exception.
* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by HoussemTN** [comment]
Hello Zakiabouzahra,

I think you are using flutter latest version.
The application runs with these versions:

  dart: ">=2.4.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0" 
  
 I'll try to update it when I have free time.

**Comment by mikealphakilo** [comment]
plz update its still not updated yet

**Comment by mikealphakilo** [comment]
this doesnt work

**Comment by mikealphakilo** [comment]
i have updated dart and flutter versions in pubspec.lck but still getting the same error

**Comment by mikealphakilo** [comment]
> Launching lib\main.dart on MAR LX1A in debug mode...
> /C:/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.6.9/lib/src/gesture/extended_image_slide_page_route.dart:331:9: Error: No named parameter with the name 'animation'.
> animation: animation,
> ^^^^^^^^^
> /C:/flutter/packages/flutter/lib/src/cupertino/route.dart:524:3: Context: Found this candidate, but the arguments don't match.
> CupertinoFullscreenDialogTransition({
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> /C:/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.6.9/lib/src/extended_image.dart:701:44: Error: No named parameter with the name 'nullOk'.
> _invertColors = MediaQuery.of(context, nullOk: true)?.invertColors ??
> ^^^^^^
> /C:/flutter/packages/flutter/lib/src/widgets/media_query.dart:818:25: Context: Found this candidate, but the arguments don't match.
> 
> static MediaQueryData of(BuildContext context) {
> ^^
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035
> * What went wrong:
>   Execution failed for task ':app:compileFlutterBuildDebug'.
> 
> > Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 13s
> Exception: Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)

Still getting error

**Comment by HoussemTN** [comment]
You have to use these versions : 
dart: ">=2.4.0 <3.0.0"
flutter: ">=1.12.13+hotfix.4 <2.0.0"
Updating them will not fix the problem.
Lots of plugins are updated.
I'll maybe rework this application in the future.
But this will not happen in the near future.
